channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.4
  - pip=24.0
  - numpy=1.26.0
  - pillow=10.4.0
  - pytorch=2.3.0
  - ipykernel=6.28.0
  - torchvision=0.18.1=cpu_py312h5f70645_1
  - pip:
    - ffmpeg-python==0.2.0